var data = [
            ['gb-ba', 1],
            ['gb-bn', 1],
            ['gb-bz', 1],
            ['gb-be', 1],
            ['gb-cy', 1],
            ['gb-ef', 1],
            ['gb-gr', 1],
            ['gb-hk', 1],
            ['gb-hf', 1],
            ['gb-hv', 1],
            ['gb-hu', 1],
            ['gb-it', 1],
            ['gb-kc', 1],
            ['gb-lw', 1],
            ['gb-nh', 1],
            ['gb-su', 1],
            ['gb-th', 1],
            ['gb-wf', 1],
            ['gb-we', 1],
            ['gb-7122', 1],
            ['gb-7123', 1],
            ['gb-7125', 1],
            ['gb-7124', 1],
            ['gb-3266', 1],
            ['gb-7127', 1],
            ['gb-7126', 1],
            ['gb-7129', 1],
            ['gb-7121', 1],
            ['gb-2364', 1],
            ['gb-7119', 1],
            ['gb-7118', 1],
            ['gb-zg', 1],
            ['gb-cc', 1],
            ['gb-7135', 1],
            ['gb-7136', 1],
            ['gb-3267', 1],
            ['gb-7134', 1],
            ['gb-7116', 1],
            ['gb-2367', 1],
            ['gb-7113', 1],
            ['gb-7114', 1],
            ['gb-7115', 1],
            ['gb-2377', 1],
            ['gb-7142', 1],
            ['gb-7138', 1],
            ['gb-7137', 1],
            ['gb-7141', 1],
            ['gb-7140', 1],
            ['gb-7139', 1],
            ['gb-7131', 1],
            ['gb-7142', 1],
            ['gb-wl', 1],
            ['gb-7132', 1],
            ['gb-3265', 1],
            ['gb-7133', 1],
            ['gb-hp', 1],
            ['gb-mb', 1],
            ['gb-rc', 1],
            ['gb-zt', 1],
            ['gb-da', 1],
            ['gb-pb', 1],
            ['gb-iw', 1],
            ['gb-mo', 1],
            ['gb-ag', 1],
            ['gb-el', 1],
            ['gb-sm', 1],
            ['gb-ci', 1]
];
$(function () {
    $('#container').highcharts('Map', {
        title: {
            text: 'Most Deprived Areas - 2019'
        },

        mapNavigation: {
            enabled: true,
            verticalAlign: 'left'
        },

        colorAxis: {
            min: 0
        },

        series: [{
            data: [['gb-ba', 1],
            ['gb-bn', 1],
            ['gb-bz', 1],
            ['gb-be', 1],
            ['gb-cy', 1],
            ['gb-ef', 1],
            ['gb-gr', 1],
            ['gb-hk', 1],
            ['gb-hf', 1],
            ['gb-hv', 1],
            ['gb-hu', 1],
            ['gb-it', 1],
            ['gb-kc', 1],
            ['gb-lw', 1],
            ['gb-nh', 1],
            ['gb-su', 1],
            ['gb-th', 1],
            ['gb-wf', 1],
            ['gb-we', 1],
            ['gb-7122', 1],
            ['gb-7123', 1],
            ['gb-7125', 1],
            ['gb-7124', 1],
            ['gb-3266', 1],
            ['gb-7127', 1],
            ['gb-7126', 1],
            ['gb-7129', 1],
            ['gb-7121', 1],
            ['gb-2364', 1],
            ['gb-7119', 1],
            ['gb-7118', 1],
            ['gb-zg', 1],
            ['gb-cc', 1],
            ['gb-7135', 1],
            ['gb-7136', 1],
            ['gb-3267', 1],
            ['gb-7134', 1],
            ['gb-7116', 1],
            ['gb-2367', 1],
            ['gb-7113', 1],
            ['gb-7114', 1],
            ['gb-7115', 1],
            ['gb-2377', 1],
            ['gb-7142', 1],
            ['gb-7138', 1],
            ['gb-7137', 1],
            ['gb-7141', 1],
            ['gb-7140', 1],
            ['gb-7139', 1],
            ['gb-7131', 1],
            ['gb-7142', 1],
            ['gb-wl', 1],
            ['gb-7132', 1],
            ['gb-3265', 1],
            ['gb-7133', 1],
            ['gb-hp', 1],
            ['gb-mb', 1],
            ['gb-rc', 1],
            ['gb-zt', 1],
            ['gb-da', 1],
            ['gb-pb', 1],
            ['gb-iw', 1],
            ['gb-mo', 1],
            ['gb-ag', 1],
            ['gb-el', 1],
            ['gb-sm', 1],
            ['gb-ci', 1]
        ],
            mapData: Highcharts.maps['countries/gb/gb-all'],
            name: 'Least Deprived',
            states: {
                hover: {
                    color: '#e82323'
                }
            },
            dataLabels: {
                enabled: true,
                format: '{point.name}'
            }
        }]
    });
});
