var data = [
    ['gb-dh', 1],
    ['gb-da', 1],
    ['gb-hp', 1],
    ['gb-mb', 1],
    ['gb-rc', 1],
    ['gb-zt', 1],
    ['gb-ha', 1],
    ['gb-zh', 1],
    ['gb-2318', 1],
    ['gb-gc', 1],
    ['gb-mk', 1],
    ['gb-bu', 1],
    ['gb-bn', 1],
    ['gb-bs', 1],
    ['gb-ns', 1],
    ['gb-sj', 1],
    ['gb-2389', 1],
    ['gb-ds', 1],
    ['gb-2391', 1],
    ['gb-ht', 1],
    ['gb-cm', 1],
    ['gb-kh', 1],
    ['gb-ne', 1],
    ['gb-ba', 1],
    ['gb-xb', 1],
    ['gb-ke', 1],
    ['gb-bz', 1],
    ['gb-be', 1],
    ['gb-cn', 1],
    ['gb-eg', 1],
    ['gb-ef', 1],
    ['gb-gr', 1],
    ['gb-hf', 1],
    ['gb-hu', 1],
    ['gb-it', 1],
    ['gb-kc', 1],
    ['gb-cy', 1],
    ['gb-me', 1],
    ['gb-rb', 1],
    ['gb-ru', 1],
    ['gb-su', 1],
    ['gb-th', 1],
    ['gb-wf', 1],
    ['gb-ww', 1],
    ['gb-we', 1],
    ['gb-li', 1],
    ['gb-bf', 1],
    ['gb-ld', 1],
    ['gb-nm', 1],
    ['gb-am', 1],
    ['gb-bb', 1],
    ['gb-cr', 1],
    ['gb-dn', 1],
    ['gb-ci', 1]
];
$(function () {
$('#container1').highcharts('Map', {
title: {
    text: 'Most Deprived Areas - 2015'
},

mapNavigation: {
    enabled: true,
    verticalAlign: 'left'
},

colorAxis: {
    min: 0
},

series: [{
    data: [    ['gb-dh', 1],
    ['gb-da', 1],
    ['gb-hp', 1],
    ['gb-mb', 1],
    ['gb-rc', 1],
    ['gb-zt', 1],
    ['gb-ha', 1],
    ['gb-zh', 1],
    ['gb-2318', 1],
    ['gb-gc', 1],
    ['gb-mk', 1],
    ['gb-bu', 1],
    ['gb-bn', 1],
    ['gb-bs', 1],
    ['gb-ns', 1],
    ['gb-sj', 1],
    ['gb-2389', 1],
    ['gb-ds', 1],
    ['gb-2391', 1],
    ['gb-ht', 1],
    ['gb-cm', 1],
    ['gb-kh', 1],
    ['gb-ne', 1],
    ['gb-ba', 1],
    ['gb-xb', 1],
    ['gb-ke', 1],
    ['gb-bz', 1],
    ['gb-be', 1],
    ['gb-cn', 1],
    ['gb-eg', 1],
    ['gb-ef', 1],
    ['gb-gr', 1],
    ['gb-hf', 1],
    ['gb-hu', 1],
    ['gb-it', 1],
    ['gb-kc', 1],
    ['gb-cy', 1],
    ['gb-me', 1],
    ['gb-rb', 1],
    ['gb-ru', 1],
    ['gb-su', 1],
    ['gb-th', 1],
    ['gb-wf', 1],
    ['gb-ww', 1],
    ['gb-we', 1],
    ['gb-li', 1],
    ['gb-bf', 1],
    ['gb-ld', 1],
    ['gb-nm', 1],
    ['gb-am', 1],
    ['gb-bb', 1],
    ['gb-cr', 1],
    ['gb-dn', 1],
    ['gb-ci', 1]
],
    mapData: Highcharts.maps['countries/gb/gb-all'],
    name: 'Least Deprived',
    states: {
        hover: {
            color: '#e82323'
        }
    },
    dataLabels: {
        enabled: true,
        format: '{point.name}'
    }
}]
});
});
